// <auto-generated />
namespace ED.Atlas.Svc.TC.Ice.FE.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class MarketTypeToPropertyMaps : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MarketTypeToPropertyMaps));
        
        string IMigrationMetadata.Id
        {
            get { return "201802210921064_MarketTypeToPropertyMaps"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
